[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mugen_python"
version = "1.0.0"
description = "Flemme de coder en anglaisğŸ™„â™¾"
readme = "README.md"
requires-python = ">=3.7"
authors = [{name = "Money Mugenâ™¾ï¸â™¾ï¸"}]

[project.scripts]
mgpy = "mugen.executeur:cli"
