[project]
name = "mugen_python"
version = "1.0.0"
description = "Flemme de coder en anglais."
readme = "README.md"
authors = [
    { name="Money Mugen♾️♾️" }
]
license = { text = "MIT" }
requires-python = ">=3.7"

[project.scripts]
mgpy = "mugen.execute:cli"
